### ISSUE TITLE
What about node-sass-chokidar since node-sass is defined as deprecated ?

### ISSUE THREAD

**Issue by jeanphiB** [michaelwayman/node-sass-chokidar#103]
Hi,
Node-sass is defined as deprecated since Oct, 26 : [https://sass-lang.com/blog/libsass-is-deprecated](https://sass-lang.com/blog/libsass-is-deprecated)
This page proposes "If you’re a user of Node Sass, migrating to Dart Sass is straightforward: just replace node-sass in your package.json file with sass."
Do you think to apply this proposed recommandation ?

**Comment by michaelwayman** [comment]
What is your proposal exactly? I only made node-sass-chokidar for the better performance because gaze sucks when it comes to normalizing fs events in virtual environments. I'm not up to much at the moment so I'd be willing to work on something. What were you thinking exactly? And forgive me if I'm being too direct, it's 5:40AM on the east coast and haven't slept yet **shrugs**

**Comment by jeanphiB** [comment]
Thank you for your prompt reply, but relax, I don't think that is a big urgency, you can sleep and proceed later ;-)
My proposal : change the dependency of node-sass-chokidar from node-sass to [Dart sass](https://github.com/sass/dart-sass) as proposed by sass-lang.com.

**Comment by michaelwayman** [comment]
@jeanphiB 
After taking a look at it it's not the easiest switch.
The issue with node-sass was that it always used gaze however taking a look at the node cli for dart sass it looks like they are using chokidar themselves which solves why I made this project in the first place.

It's going to be sad to deprecate node-sass-chokidar since it's my most popular repo but dart sass is simply better with more people working on it.
