### ISSUE TITLE
Support ignoring files (esp. during --watch)

### ISSUE THREAD

**Issue by rshk** [michaelwayman/node-sass-chokidar#24]
My problem: Emacs creates lockfiles, named something like `.#filename.scss`, when the file is edited. 

They're "broken" symlinks, pointing to a target like `user@host.pid:timestamp`, and they're automatically deleted once the file is saved. Unfortunately, picking them up causes the build process to choke with an `ENOENT`.
This didn't happen as often with node-sass, because it's broken and tends to fail picking up new files.

Some ways in which this could be solved:

1. Add an option to provide extra ignore patterns, eg. ``--ignore <regex>`` (or an environment variable perhaps?)
2. Just automatically ignore hidden files, along with `_*` files here: https://github.com/michaelwayman/node-sass-chokidar/blob/master/bin/node-sass-chokidar#L366 (I don't think anyone is interested in having them built anyways)
3. Just have chokidar ignore (globs) `.*` or `.#*`. They actually do that out of the box for a bunch of common temp files, see https://github.com/paulmillr/chokidar/blob/master/index.js#L349

Probably 2 or 3 are quicker to implement; I'd imagine you'd want to avoid having to maintain a huge list of all possible temporary files to be ignored, but I guess just ignoring hidden files would be a good compromise?

**Comment by michaelwayman** [comment]
Hmm. thanks for bringing this to my attention, I can see  how this would be an issue.

I see how this can be an issue. They are all pretty good solutions.
I don't think #2 would work because _variables.scss is a common pattern, and node-sass and node-sass-chokidar both read these files in for the dependency graph, but we don't render the `_*` files out to _variables.css... I'm not a fan of "hidden magic" like in #3 so that leaves us with #1. I will try to patch this when I get time, I have just been swamped at work and other side projects. Feel free to open a PR, but I'll try to get around to it.

**Comment by liskicious** [comment]
(setq create-lockfiles nil)  in emacs config file seems to work around this issue

**Comment by rshk** [comment]
Yep.. that’s what I’m using as a workaround atm, in a dir-locals file, but I do want lock files and other editor/tools might be creating other similar files etc.

**Comment by nikolas** [comment]
I've just ran into this issue as well (https://github.com/michaelwayman/node-sass-chokidar/issues/40).

**Comment by michaelwayman** [comment]
I released version 1.0.0 of node-sass-chokidar and there is a new option `--match-regex` where you can supply a regex and everything that doesn't match will be ignored. So this should fix you're problem if not feel free to reopen the issue.

**Comment by dosentmatter** [comment]
@michaelwayman I use git submodules in my project. I read the [code](https://github.com/michaelwayman/node-sass-chokidar/blob/master/bin/node-sass-chokidar#L228-L234) and see that it only allows excluding by filename. Any chance we can allow excluding directories or a regex on the full path?.

My git submodule is a project on its own that can have `node_modules` so the path to its node_modules is `src/submodule/node_modules`. I am trying to use this regex to exclude `^(?!node_modules).*$`.

**Comment by michaelwayman** [comment]
@dosentmatter I'm assuming you still want to be able to import the `scss` files from node_modules, but you just don't want to render them correct?

Like you want to be able to  `@import "node_modules/bootstrap/scss/bootstrap.scss";` but you don't want to actually render the bootstrap.scss inside `node_modules`?

**Comment by sprlwrksAprilmintacpineda** [comment]
If you prefix an `underscore` on the filename it would not be parsed but you can still import it on your other sass files like so:

```
/ root
| -- styles
|     | --_variables.sass
|     ` -- index.sass
` -- index.js
```

**_variables.sass**

```
$background: #006699
```

**index.sass**

```
@import './variables'

body
  background: $background
```


**index.js**


```
import './styles/index.css';
```

**Comment by dosentmatter** [comment]
@sprlwrksAprilmintacpineda, thanks for the response. Unfortunately, that won't work for me because the files I am trying to exclude are not under my control. They are from a node_modules folder in a nested git submodule.

**Comment by dosentmatter** [comment]
@callain, sorry for the late response. My solution was just to build one scss file and not multiple files.

So compared to the file I posted above, I'm not building the whole src folder anymore. I'm only building `./src/index.scss`. So then it won't go down into the submodule and build `.scss` in `./src/project-b/node_modules`. If you have `.scss` that you need to build, just import it from `./src/index.scss`. A negative of this is that you can't import the local (in the same folder) `.css` from your javascript since they aren't built from `.scss`. But a positive is that it kinda shows that your CSS is global and not scoped to your javascript file (unless you are using css modules or something).

```
# build_sass.sh

#!/usr/bin/env sh

node-sass-chokidar \
  --include-path ./src \
  --include-path ./node_modules \
  ./src/index.scss ./src/index.css \
  "$@"
```

This solution works fine for me because I am using [styled-components](https://github.com/styled-components/styled-components) for locally scoped CSS. Writing `.scss` for me is mostly just for global theming and bootstrap configuration. I have a method to convert the global theming bootstrap variables into a javascript object so they are available within styled-components.

I know this solution isn't ideal, but hopefully it can work for you. The only case I can think of that doesn't work is when you need to import locally scoped CSS like in [css-modules](https://github.com/css-modules/css-modules), which you won't have access to in this solution since there will only be one `index.css`.

---

Other things you can try:
1. If the `.scss` files you are trying to exclude have unique filenames, you can try using [--match-regex](https://github.com/michaelwayman/node-sass-chokidar#options) to specify an inverse match to exclude those files.
2. If you are using create-react-app: When I was setting up my project, [react-app-rewire-sass](https://github.com/timarney/react-app-rewired/tree/master/packages/react-app-rewire-sass) was kinda abandoned. Now it has been deprecated and moved over to [react-app-rewire-scss](https://github.com/aze3ma/react-app-rewire-scss). Rewire allows you to modify create-react-app config such as webpack, jest, babel, etc. without ejecting. I haven't tried react-app-rewire-scss myself, but I've rewired other things successfully. Note that it also works for typescript - my project is in typescript. When create-react-app version 2 comes out, it will have [opt-in support for sass](https://github.com/facebook/create-react-app/pull/4195), so you could just remove the rewire and switch over to CRA2.

I hope this helped!

**Comment by dosentmatter** [comment]
@callain, yeah the only reason my solution works fine is because I don't have many .scss files.

I knew about the git dependencies, but decided not to use it. The reason was because I didn't want to have to make a commit to test changes in the top level project. I wanted to have local changes in both repositories, so I could test components in the top level project before pushing. Thanks for the suggestion though.

**Comment by jamieallen59** [comment]
I managed to do this using their `--match-regex` flag using it to remove anything that had 'node_modules' in it:

```javascript
node-sass-chokidar ./src -o src/ --match-regex '/^((?!node_modules).)*$/gm'
```

Hope it helps.
