### ISSUE TITLE
how to exclude folder, like my input is /src but i want exclude /src/assests/styles ?

### ISSUE THREAD

**Issue by softobizgit** [michaelwayman/node-sass-chokidar#95]
how to exclude folder, like my input is /src but i want exclude /src/assests/styles ?

my package.json code is here

 "build-css": "node-sass-chokidar src/ -o src/"

**Comment by michaelwayman** [comment]
There is currently an `--include-path` option. You should be able to include everything but that path. But the CLI command would probably be pretty long. I can create an `--exclude-path` option, but please give me an example project/source code to test against otherwise it might take me a while, being busy at my real job and all.
